### ISSUE TITLE
[Idea]Oil Fractioning

### ISSUE THREAD

**Issue by MrKickkiller** [BCA-Team/Buildcraft-Additions#217]
A new multiblock that can be used to fraction oil into fuel, nafta (fuel), light-oil, bitumen etc.
Eg: See picture
Usage case: Different fuels have higher potency/ longer burn times.
Bitumen (Asfalt) as a crafting material for black road blocks or something?
Plastic / Nylon : Crafting ingredient for tier 3 KEB?
![image](https://cloud.githubusercontent.com/assets/5099359/5899635/bb440002-a55e-11e4-9fc0-37844dded53e.png)

**Comment by AEnterprise** [comment]
this actually is how the multiblock refinery idea started, i might take a look at this later, not sure if it'll be for 2.0 or a later release though, the original idea was to have refinery output a gas and the multiple outputs would come from the cooling tower

**Comment by Speiger** [comment]
A few things about that idea. I did cover that a little bit with some people (in real live) and we talked about the pros and contras about the differend fuels. I do not have everything in mind yet (still searching for that memory in my mind), but differend Type of Fuels have at differend states (speedStats) better/lesser effencies. (Totally typed it wrong). So maybe BC could override its fuel information. There could be a basic registry and advanced registry.

And if that will be not the case then make it that all these fuels get their own base production.

**Comment by MrKickkiller** [comment]
@Speiger I make from your comment that you find the idea of different fuels with each different power characteristics interesting.

Eg=
Fuel = 6mj/t ,medium burn time
Liquified Petroleum Gas (LPG for short) = Higher mj/t, but lower burn time
Heavy alkanes = Low mj/t but last for eternity

**Comment by Speiger** [comment]
Good start but you missunderstood me.
The mainidea was this: (I talk only about the speed the engine moves not the temperature!)
Diesel: (fuel usage is still the same)
 Blue State: 4 MJ per tick
 Green State: 6 MJ per tick.
 Yellow State: 8 MJ per tick
 Red State: 10 MJ Per tick.

Benzin:
 Blue State: 8 MJ per tick
 Green State: 7,5 MJ per tick
 Yellow State: 6,5 MJ per tick
 Red State: 5 MJ per tick.


And for coolant: 
(Water is the example)  (lets say the engine uses when it heated up 1 mB water per tick)(the required water amount is compareable how much it produce at that state biome can effect it)
 Blue State: 0,5 mB per tick
 Green State: 1 mB per tick
 Yellow State: 2 mB per tick
 Red State: 4-5 mB per tick. 

So that the piston speed affects the effency. I think that should be right that diesel has the best efficy at higher momentum and benzin at low momentum.

That also should be a little bit more of a challange and not only a you put fuel and Water/coolant/liquidIce in and it runs perfectly.

Maybe a way with gates to tell where it should hold the state. Else it just try to keep the highest state. And removing the redstone signal just shutdown the engine and you can restart it always even it is not 100% down.

**Comment by AEnterprise** [comment]
@Speiger what you are sugestion would require alot of rewriting of how engines work and i don't think @asiekierka is gona agree to that

**Comment by Speiger** [comment]
We will see. And if asie is against it then i have no problem with that at all. It is just an idea.
