### ISSUE TITLE
kinetic backpack

### ISSUE THREAD

**Issue by AEnterprise** [BCA-Team/Buildcraft-Additions#277]
kinetic capsules with some plating (maybe a new kind, not sure yet) makes the kinetic backpack and you would be able to put it in your chest slot, it would have a little cable comming out leading to your hand, if you're holding a RF chargable tool it will charge it

credit to chilm for the original idea

**Comment by iTitus** [comment]
Sounds very nice ;)

**Comment by BigXplosion** [comment]
awesome idea

**Comment by AEnterprise** [comment]
as for making it i'm thinking custom crafting mechanic: make a frame and then solder the capsules to it, also a new tool to break off soldered capsules, very small chanse to recover the capsule that way, but very large chanse you get a broken capsule instead, maybe also a medium chanse that you damange that part of the backpack

**Comment by iTitus** [comment]
Soldering sounds very nice :)
Hehehe, all those ideas...

**Comment by yt-chilm** [comment]
maybe you can opt to fuse plates on in places instead of capsules to add armour and so the user can balance up protection vs power? would that work?

**Comment by yt-chilm** [comment]
(plus later plug in the cables to shoes, helmet etc) xD

**Comment by AEnterprise** [comment]
soldering plating over the kinetic capsule should be doable, same princible then i guess, you can get it off but not without damanging it (they would have to melt it to get it back intro shape i sugest)

later extensions to other armour slots should also be possible, not sure what exactly they will do and how they will work though

**Comment by anti344** [comment]
Uh, another thing to block out chestplate slot. I like the idea, but why always my chest slot?
U can simply occupy, like, slot 35(in the corner of inventory) and even write a little API(to automatically stack up `functional` slots for mod support).

**Comment by yt-chilm** [comment]
A Batt-belt maybe? (hehehe)

**Comment by AEnterprise** [comment]
it's a 'backpack' so it makes sense to me to put it on your back, also for clarity toward the player, puting it in a specific slot in your inventory or in any slot could also work but would be confusing for the player

**Comment by anti344** [comment]
Well, now it's not a 'kinetic backpack', now it's a 'kinetic recharger thingy-dingy' =D

**Comment by leSamo** [comment]
Basicly like IC2 batpack?

**Comment by AEnterprise** [comment]
similar but not the same thing

**Comment by Speiger** [comment]
XD yeah because its a differend type of energy. Also i would tell you @AEnterprise to use the IC2 Way to save lag and to prevent a bug.
Instead of the Kinectic pack sending energy constantly you should make it that the Tools request energy from the Kinectic pack when they draw it from the tool (so if a pack is there the tool drain it from there and if not it drains it from itself.), that prevents the bug i had that tools can not mine blocks because they get recharged, (NBTUpdate resets the item which automaticly resets the current miningstate, because the item did change).

**Comment by AEnterprise** [comment]
@Speiger i'll see how i do it, the tool requesting energy might be a good idea but not sure if i'll do it. i think i want other RF powered tools also to be charged by it

also a change in powerlevel shouldn't prevent the tool from breaking a block, if that's the case then it's due to a fault in the tool's code

**Comment by Speiger** [comment]
I made Portable Engines in my Mod and they powered my Pneumatic drill (The Engine was producing 1 MJ per tick, until the Drill was fully charged i was not able to mine a block because it was to slow and the item got resynced every time. 
Here you have a part of my TinyChest code how i made it:
Pneumatic drill (Just you know how i made my tool): 
https://www.dropbox.com/s/eyrdnifntol8gto/ItemBCDrill.java?dl=0
And here is my Portable Engine code(I know it is a mess but it was the mod where i learned coding with):
https://www.dropbox.com/s/fr9m9vw2w5rgt8z/ItemPortableEngine.java?dl=0

And the bug i had was every time the drill got recharged it was not able to mine. (TE3 Do not have the problem because the Recharge rate is insane. But if you have a Recharge rate of 1 RF per tick then you will have the same problem).

**Comment by AEnterprise** [comment]
done
