### ISSUE TITLE
Packet exception handling bcadditions channel causes fatal error

### ISSUE THREAD

**Issue by cocopuffs99** [BCA-Team/Buildcraft-Additions#384]
Hey Guys,

In the latest BCA version I am getting a "Connection Lost: A fatal error has occurred, this connection is terminated" error that resets me to the title screen for my MC client.  The ATLauncher log states:

[Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel bcadditions
[14/4/2015 11:39:35 AM] io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(4) exceeds writerIndex(13): SlicedByteBuf(ridx: 12, widx: 13, cap: 13/13, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 14, cap: 14/14))

This happened when I was placing a semi-automatic duster next to a heated furnace that already had 3 coils next to it (originally 4 coils, I removed one coil and in its place put the semi-automatic duster in the same voxel space to produce the crash.

Full ATLauncher log: http://paste.atlauncher.com/view/90ed6501

Thanks for an awesome mod. The Eureka system is nice, got me back into BCA again =)

**Comment by AEnterprise** [comment]
hmm, try to track this down

**Comment by Speiger** [comment]
@AEnterprise that is a really hard bug. I had almost the same problem with IC2 Classic.
The system i cam up with was that i used the FMLIndexedMessageToMessageCodec for the channel manager & the SimpleChannelInboundHandler for the packet handler.
That thing works a little bit differend then your system but you only need to handle the PacketReceiving&Sending only 1 Time. Also you can handle own functions with that.
But that solves not your problem...

To solve your problem you need to send an information what you will get.
That is easier then you think you can send just a number with the packet which the receiver knows: aha i have todo now this and this.
Also another thing i would mention: Do not send always every data. Send only the nessesary data. Because Minecraft does every time you open the gui/the tileEntity get sync the writeToNBT/readFromNBT will be called anyways...

**Comment by AEnterprise** [comment]
yeah it's a touch nut to crack, i'm thinking of sending an identifier allong with the data that the machine checks on sync, also gona surround the reading call with a try-catch that just logs the error in the log as i suspect this is just packet A from machine A ending up at machine B

**Comment by Speiger** [comment]
I would say that you use Strings because they are harded to match then a Integer.
Also you need to send a Identifier for the Data amount. Not only the TileEntity should randomly add data to the thing. The Packets should be set by creation. To the adding and reading you should use Data Input/Output Streams because they have more functions/supports that make codewise a lot of stuff easier. Also you can see how much data get inserted and how much you can read out...
Here an example. It is IC2 Classic code (my version thats why it does not fall under the licence).
https://www.dropbox.com/s/vtjka8f5z10jgdk/FieldUpdatePacket.java?dl=0
The IC2 TileEntity fields are get randomly added to the IC2 Network you can normally net expect which data get inserted. But with that code peace i see what get sended and how much. (I should have done it better (because xyz coords are more than one time in it but current way is working stable enough). I hope that helps.

**Comment by AEnterprise** [comment]
integers are easier to sync and safe enough, also the data send and expected data will always be the same, if it isn't then the packet isn't from that TE

i don't need datastreams, the current way works fine for me and i don't know enough of networking stuff nor do i have the will to rewrite my system again

and your way isn't efficient at all, using reflection for syncing is a bad idea, it's your own code so reflection is redundant and way to slow

**Comment by Speiger** [comment]
True reflection is slow but allows to sync Fields just by names. Not that is a IC2 Feature i just made it to the Current network Setup compatible. But i like the idea where you say: "Update please that field".
